# Generated by Django 3.2.1 on 2021-05-06 16:21

import common.constants.disease_category
import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at_utc', models.DateTimeField(auto_now_add=True)),
                ('modified_at_utc', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=128)),
                ('disease_severity', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(0)])),
                ('disease_category', models.CharField(choices=[('CHRONIC', 'Chronic'), ('ACUTE', 'Acute')], default=common.constants.disease_category.DiseaseCategory['CHRONIC'], max_length=32)),
            ],
            options={
                'verbose_name': 'Disease',
                'verbose_name_plural': 'Diseases',
                'db_table': 'Disease',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at_utc', models.DateTimeField(auto_now_add=True)),
                ('modified_at_utc', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=128)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('NP', 'No Preference')], max_length=16)),
                ('avatar', models.URLField(blank=True, max_length=128, null=True)),
                ('diseases', models.ManyToManyField(blank=True, to='patient.Disease')),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'db_table': 'Patient',
                'managed': True,
            },
        ),
    ]
